"""add user profile fields

Revision ID: 9d7ed1a61eec
Revises: 
Create Date: 2025-11-05 19:04:17.944346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7ed1a61eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('real_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('specialty')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('real_name')
        batch_op.drop_column('grade')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
